"""Page 2: Historical trends — annual averages 1950–2025 with per-country event lines."""
import pandas as pd
import plotly.express as px
import streamlit as st
from utils import load_scores, MEASURES, METHODOLOGY, mobile_css

st.set_page_config(page_title="Historical Trends · Observatory", layout="wide")
mobile_css()
st.title("Historical trends, 1950–2026")

GLOBAL_EVENTS = {1966: "Cultural Revolution",
                 1996: "Taiwan Strait Crisis", 2022: "Pelosi visit"}
TYPE_COLOR = {"escalation": "#b2182b", "rapprochement": "#2166ac"}


@st.cache_data
def load_events():
    return pd.read_csv("events.csv")


with st.sidebar:
    measure = st.selectbox("Index", list(MEASURES.keys()), format_func=lambda k: MEASURES[k],
                           index=list(MEASURES).index("negativity"))
    show_events = st.checkbox("Show country events (single country)", value=True)

df = load_scores("Monthly")
df["year"] = df["period"].dt.year
yearly = df.groupby(["country", "year"], as_index=False)[measure].mean()
yearly = yearly[(yearly["year"] >= 1950) & (yearly["year"] <= 2026)]

countries = sorted(yearly["country"].unique())
pick = st.multiselect("Countries", countries, default=["US", "Russia", "Japan"])
sub = yearly[yearly["country"].isin(pick)]

fig = px.line(sub, x="year", y=measure, color="country",
              labels={measure: MEASURES[measure], "year": ""})

# global (China-domestic) events — always, faint grey
for yr, name in GLOBAL_EVENTS.items():
    fig.add_vline(x=yr, line_dash="dot", line_color="lightgrey")
    fig.add_annotation(x=yr, y=1, yref="paper", text=name, showarrow=False, textangle=-90,
                       font=dict(size=9, color="grey"), xshift=-7, yanchor="top")

# per-country bilateral events — only when exactly one country is selected (else too busy)
if show_events and len(pick) == 1:
    ev = load_events()
    ev = ev[(ev.country == pick[0]) & (ev.year >= 1950) & (ev.year <= 2026)
            & (~ev.label.str.contains("Tiananmen", case=False, na=False))]
    for _, e in ev.iterrows():
        col = TYPE_COLOR.get(e["type"], "grey")
        fig.add_vline(x=e["year"], line_dash="dash", line_color=col, opacity=0.55)
        mark = "▲" if e["type"] == "escalation" else "▼"
        fig.add_annotation(x=e["year"], y=0, yref="paper", text=f"{mark} {e['label']}", showarrow=False,
                           textangle=-90, font=dict(size=9, color=col), xshift=7, yanchor="bottom")
    st.caption(f"**Events for {pick[0]}** — ▲ escalation (red), ▼ rapprochement (blue). "
               "Dashed lines = bilateral events; grey dotted = China-domestic milestones.")
elif show_events:
    st.caption("Select **exactly one** country to overlay its bilateral event timeline.")

fig.update_layout(margin=dict(l=0, r=0, t=10, b=0), legend_title="")
st.plotly_chart(fig, use_container_width=True)

st.divider()
st.caption(f"**Methodology — {MEASURES[measure]}.** {METHODOLOGY[measure]}  "
           "Annual = mean of the monthly series (empty months scored 0). Country events generated by "
           "per-country historian agents and verified against the Tsinghua relations series "
           "(50% coincide with a relations swing ≥1.0).")
